name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: ["octo-org/1", "octo-org/44"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please write a clear and concise description of what the bug is.
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behavior:\n 1. Go to '...'\n 2. Click on '....'\n 3. Scroll down to '....'\n 4. See error"
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04/Windows/MacOS
          - **Device**: PC/Steamdeck
          - **Greenlight version**: 2.0.1
      value: |
          - OS: 
          - Node: 
          - Greenlight version: 
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: duplicate
    attributes:
      label: New issue
      description: To prevent duplicated issues we check if a similar issue already exists. Please confirm that this issue is new and not a duplicate.
      options:
        - label: I confirm that this is a new issue and not a duplicate
          required: true
