name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["Feature request"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the feature should do. (example: I want to get a notification when a friend comes online)

  - type: textarea
    id: usecase
    attributes:
      label: Describe the use case
      description: |
        **Describe a use case for the feature**
        A clear and concise description of when you want to use this. (example: I want to run the application in the background and get notified when a friend comes online)

  - type: textarea
    id: other
    attributes:
      label: Additional information
      description: |
        **Additional information**   
        Add any other context or screenshots about the feature request here.