name: Other
description: File a bug report
title: ''
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Other
      description: |
        ** Please use the bug and feature request templates when applicable **
