name: Build/flatpak

on:
  push:
    branches:
      - main-v2
      - feature/*
    tags:
      - v*
  pull_request:
    branches:
      - main-v2
      
# env:
#   DEBUG: '*'

jobs:
  flatpak:
    name: Flatpak Build
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      # - name: Set up node_modules cache
      #   uses: actions/cache@v3
      #   continue-on-error: false
      #   with:
      #     path: |
      #       node_modules/           
      #       xal-node/node_modules/           
      #     key: ${{ runner.os }}-${{ runner.arch }}-npm-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: ${{ runner.os }}-${{ runner.arch }}-npm-

      # - name: Install yarn
      #   run: npm install -g yarn

      # - name: Install yarn dependencies
      #   run: yarn

      - name: Set up flatpak build cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            build/           
            .flatpak-builder/           
          key: ${{ runner.os }}-${{ runner.arch }}-flatpak-builder-${{ hashFiles('flatpak/*') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-flatpak-builder-

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: greenlight.flatpak
          manifest-path: flatpak/dev.unknownskl.greenlight.yml
          cache-key: flatpak-builder-${{ github.sha }}